project:
  type: website
  output-dir: docs
execute:
  freeze: auto
website:
  title: "Damrauer Lab"
  page-navigation: true
  favicon: "favicon_io/apple-touch-icon.png"
  sidebar:
    search: true
    style: "docked"
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/mglev1n/damrauer-lab
          - text: Report a Bug
            url:  http://github.com/mglev1n/damrauer-lab/issues/new
    contents:
      - href: "index.qmd"
      - section: "Getting Started"
        contents:
        - href: "lpc.qmd"
        - href: "rstudio.qmd"
        - href: "tools.qmd"
  repo-url: https://github.com/mglev1n/damrauer-lab
  repo-subdir: "docs"
  repo-branch: "master"
  repo-actions: [edit, issue]
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


